version: '3.8'

services:
  quarkus-app:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS_APPEND=-Dquarkus.http.host=0.0.0.0
    volumes:
      - ./target/quarkus-app:/deployments
    entrypoint: [ "/opt/jboss/container/java/run/run-java.sh" ]