version: "3"

services:
  BFF:
    image: "nestjs-restaurant/bff"
    restart: always
    ports:
      - 8080:8080
    environment:
      - MENU_SERVICE_URL_WITH_PORT=${MENU_SERVICE}:3000
      - KITCHEN_SERVICE_URL_WITH_PORT=${KITCHEN_SERVICE}:3000
      - DINING_SERVICE_URL_WITH_PORT=${DINING_SERVICE}:3000
    networks:
      - nestjs-restaurant-network
networks:
  nestjs-restaurant-network:
    driver: bridge
